server:
  port: 8081

spring:
  application:
    name: gmart

  datasource:
    url: jdbc:mysql://localhost:3306/gmart_db
    username: crane
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security: DEBUG