server:
  port: 8081


#파일 업로드 디렉토리 설정
file:
  upload-dir: ../ProfileImage

storage:
  type: local

spring:
  application:
    name: gmart

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  mvc:
    static-path-pattern: /profile-images/**

  web:
    resources:
      static-locations: file:///C:/Users/dlwns/crane/PROJECT_GMART/Spring Boot/ProfileImage/


  datasource:
    url: jdbc:mysql://localhost:3306/gmart_db
    username: crane
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security: DEBUG

mybatis:
  type-aliases-package: gmart.gmart.domain, gmart.gmart.dto.mybatis
  configuration:
    map-underscore-to-camel-case: true


jwt:
  issuer: dlwnsgkr8318@skuniv.ac.kr
  access-secret-key: asdasjvnoansckln12359449asddafkmsbxibuoiuoiuqwepppokkasf2asd
  refresh-secret_key: asfacolkasndlknv3203klfamkld02asdkjfajkvnlancdkdklmasdklv